-- root = "./"
-- thread = 8
-- logger = nil
-- harbor = 0
-- start = "main"	-- main script
-- bootstrap = "snlua bootstrap"	-- The service for bootstrap
-- luaservice = root.."service/?.lua;"..root.."test/?.lua;"..root.."examples/?.lua"
-- lualoader = "lualib/loader.lua"
-- snax = root.."examples/?.lua;"..root.."test/?.lua"
-- cpath = root.."cservice/?.so"

root = "./zero/"
thread = 1
logger = nil
harbor = 0
start = "zero"	-- main script
bootstrap = "snlua bootstrap"	-- The service for bootstrap
luaservice = root.."?.lua;"..root.."service/?.lua"
lua_path = root.."lualib/?.lua"
lualoader = root.."lualib/loader.lua"
cpath = root.."?.dll"
